powerquery:
*Anime:
let
    Source = Csv.Document(File.Contents("C:\Users\21650\Downloads\anime reviews\anime-dataset-2023.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"anime_id", Int64.Type}, {"Name", type text}, {"English name", type text}, {"Other name", type text}, {"Score", type number}, {"Genres", type text}, {"Synopsis", type text}, {"Type", type text}, {"Episodes", type text}, {"Aired", type text}, {"Premiered", type text}, {"Status", type text}, {"Producers", type text}, {"Licensors", type text}, {"Studios", type text}, {"Source", type text}, {"Duration", type text}, {"Rating", type text}, {"Rank", Int64.Type}, {"Popularity", Int64.Type}, {"Favorites", Int64.Type}, {"Scored By", Int64.Type}, {"Members", Int64.Type}, {"Image URL", type text}}),
    #"Replaced UKNOWN with null" = Table.ReplaceValue(#"Changed Type","UNKNOWN",null,Replacer.ReplaceValue,{"English name","Type","Genres","Episodes", "Premiered","Producers","Licensors","Studios","Rating","Rank"}
),
    #"Replaced Unknown with null" = Table.ReplaceValue(#"Replaced UKNOWN with null","Unknown",null,Replacer.ReplaceValue,{"Source","Duration"}),
    #"Replaced Errors in Scored By column" = Table.ReplaceErrorValues(#"Replaced Unknown with null", {{"Scored By", null}}),
    #"Replaced Errors in Score column" = Table.ReplaceErrorValues(#"Replaced Errors in Scored By column", {{"Score", null}}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Replaced Errors in Score column", "Text Before Delimiter", each Text.BeforeDelimiter([Name], " ("), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Inserted Text Before Delimiter",{"Name","Image URL", "Synopsis"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Text Before Delimiter", "Name"}}),
    #"Changed Episodes type from decimal to integer" = Table.TransformColumnTypes(#"Renamed Columns",{{"Episodes", Int64.Type}}),
    #"Duplicated Aired Column" = Table.DuplicateColumn(#"Changed Episodes type from decimal to integer", "Aired", "Airing Period"),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Aired Column", "Aired", Splitter.SplitTextByDelimiter("to", QuoteStyle.Csv), {"Began Airing", "Ended Airing"}),
    #"Trimmed Ended Airing Column" = Table.TransformColumns(#"Split Column by Delimiter",{{"Ended Airing", Text.Trim, type text}}),
    #"Replaced ? with null in Ended Airing Column" = Table.ReplaceValue(#"Trimmed Ended Airing Column","?",null,Replacer.ReplaceValue,{"Ended Airing"}),
    #"Fixed Began Airing Through Custom Function" = Table.AddColumn(#"Replaced ? with null in Ended Airing Column", "Began Airing Fixed", each let
    Raw = [Began Airing],
    Value = if Raw = null then null else Text.Trim(Raw),
    Words = if Value = null then {} else Text.Split(Value, " "),
    IsNA = Value <> null and Text.Lower(Value) = "not available",
    IsYearOnly = Value <> null and Text.Length(Value) = 4 
                 and (try Number.From(Value) otherwise null) <> null,
    IsMonthYear = Value <> null and not IsYearOnly and List.Count(Words) = 2 
                  and (try Number.From(Words{1}) otherwise null) <> null
in
    if Value = null or IsNA then null
    else if IsYearOnly then #date(Number.From(Value), 1, 1)
    else if IsMonthYear then 
        #date(Number.From(Words{1}), Date.Month(Date.FromText(Words{0} & " 1, 2000")), 1)
    else Date.FromText(Value)),
    #"Removed Began Airing" = Table.RemoveColumns(#"Fixed Began Airing Through Custom Function",{"Began Airing"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Began Airing",{{"Began Airing Fixed", "Began Airing"}}),
    #"Changed Type from text to date" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Began Airing", type date}, {"Ended Airing", type date}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type from text to date", "Duration (min)", each let
    Raw = if [Duration] = null then null else Text.Trim([Duration]),

    HasHr = Raw <> null and Text.Contains(Raw, "hr"),
    Hours = if HasHr then Number.From(Text.Trim(Text.BeforeDelimiter(Raw, "hr"))) else 0,

    Remainder = if HasHr then Text.AfterDelimiter(Raw, "hr") else Raw,
    HasMin = Remainder <> null and Text.Contains(Remainder, "min"),
    Minutes = if HasMin then Number.From(Text.Trim(Text.BeforeDelimiter(Remainder, "min"))) else 0,

    Total = if Raw = null then null else Hours * 60 + Minutes
in
    Total),
    #"Replaced Errors in Rank Column" = Table.ReplaceErrorValues(#"Added Custom", {{"Rank", null}}),
    #"Replaced Rank and Popularity zeros to null" = Table.ReplaceValue(#"Replaced Errors in Rank Column",0,null,Replacer.ReplaceValue,{"Rank", "Popularity"}),
    #"Replaced Value" = Table.ReplaceValue(#"Replaced Rank and Popularity zeros to null","Not available",null,Replacer.ReplaceValue,{"Airing Period"}),
    #"Added Unique Display Name Column" = Table.AddColumn(#"Replaced Value", "Display Name", each 
    (if Text.Length([Name]) > 40 then Text.Start([Name], 40) & "..." else [Name])
    & " (" & (if [Type] <> null then [Type] else "") & 
    (if [Premiered] <> null then ", " & [Premiered] else 
     if [Began Airing] <> null then ", " & Date.ToText([Began Airing], "yyyy") else "") & ")"),
    #"Inserted Year" = Table.AddColumn(#"Added Unique Display Name Column", "Premier Year", each Date.Year([Began Airing]), Int64.Type),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Year",{"anime_id", "Display Name", "Name", "English name", "Other name", "Score", "Genres", "Type", "Episodes", "Began Airing", "Ended Airing", "Airing Period", "Premiered","Premier Year", "Status", "Producers", "Licensors", "Studios", "Source", "Duration", "Duration (min)", "Rating", "Rank", "Popularity", "Favorites", "Scored By", "Members"}),
    #"Removed Rows With Mostly Null Entries" = Table.SelectRows(#"Reordered Columns", each not ([Type] = null and [Members] = 0 and [Favorites] = 0)),
    #"Removed Rows With Mostly Null Entries and Not Yet Aired Status" = Table.SelectRows(#"Removed Rows With Mostly Null Entries", each  not ([Status] = "Not yet aired" and [Members] = 0 and [Favorites] = 0))
in
    #"Removed Rows With Mostly Null Entries and Not Yet Aired Status"

*Anime Genres: let
    Source = Anime,
    #"Removed Other Columns" = Table.SelectColumns(Source,{"anime_id", "Name", "Genres"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Other Columns", "Genres", Splitter.SplitTextByDelimiter(",", QuoteStyle.None), {"Genres.1", "Genres.2", "Genres.3", "Genres.4", "Genres.5", "Genres.6", "Genres.7", "Genres.8", "Genres.9"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Genres.1", type text}, {"Genres.2", type text}, {"Genres.3", type text}, {"Genres.4", type text}, {"Genres.5", type text}, {"Genres.6", type text},{"Genres.7", type text},{"Genres.8", type text},{"Genres.9", type text}}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"anime_id", "Name"}, "Attribute", "Genre"),
    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Attribute"}),
    #"Trimmed Text" = Table.TransformColumns(#"Removed Columns",{{"Genre", Text.Trim, type text}})
in
    #"Trimmed Text"

*Anime_Studios:
let
    Source = Anime,
    #"Removed Other Columns" = Table.SelectColumns(Source,{"anime_id", "Name", "Studios"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Other Columns", "Studios", Splitter.SplitTextByDelimiter(",", QuoteStyle.None), {"Studios.1", "Studios.2", "Studios.3", "Studios.4", "Studios.5", "Studios.6", "Studios.7", "Studios.8", "Studios.9", "Studios.10"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Studios.1", type text}, {"Studios.2", type text}, {"Studios.3", type text}, {"Studios.4", type text}, {"Studios.5", type text}, {"Studios.6", type text}, {"Studios.7", type text}, {"Studios.8", type text}, {"Studios.9", type text}, {"Studios.10", type text}}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"anime_id", "Name"}, "Attribute", "Studio"),
    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Attribute"}),
    #"Trimmed Text" = Table.TransformColumns(#"Removed Columns",{{"Studio", Text.Trim, type text}})
in
    #"Trimmed Text"

*Top_Studios:
let
    Source = Anime_Studios,
    #"Grouped Rows" = Table.Group(Source, {"Studio"}, {{"Anime_Produced_Count", each Table.RowCount(_), Int64.Type}}),
    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"Anime_Produced_Count", Order.Descending}}),
    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each [Anime_Produced_Count] >= 10),
    #"Added Index" = Table.AddIndexColumn(#"Filtered Rows", "Index", 1, 1, Int64.Type),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Studio", "Anime_Produced_Count"})
in
    #"Reordered Columns"

*Anime_Grouped_By_Name:
let
    Source = Csv.Document(File.Contents("C:\Users\21650\Downloads\anime reviews\anime-dataset-2023.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"anime_id", Int64.Type}, {"Name", type text}, {"English name", type text}, {"Other name", type text}, {"Score", type number}, {"Genres", type text}, {"Synopsis", type text}, {"Type", type text}, {"Episodes", type text}, {"Aired", type text}, {"Premiered", type text}, {"Status", type text}, {"Producers", type text}, {"Licensors", type text}, {"Studios", type text}, {"Source", type text}, {"Duration", type text}, {"Rating", type text}, {"Rank", Int64.Type}, {"Popularity", Int64.Type}, {"Favorites", Int64.Type}, {"Scored By", Int64.Type}, {"Members", Int64.Type}, {"Image URL", type text}}),
    #"Replaced UKNOWN with null" = Table.ReplaceValue(#"Changed Type","UNKNOWN",null,Replacer.ReplaceValue,{"English name","Genres","Episodes", "Premiered","Producers","Licensors","Studios","Rating","Rank"}
),
    #"Replaced Unknown with null" = Table.ReplaceValue(#"Replaced UKNOWN with null","Unknown",null,Replacer.ReplaceValue,{"Source","Duration"}),
    #"Replaced Errors in Scored By column" = Table.ReplaceErrorValues(#"Replaced Unknown with null", {{"Scored By", null}}),
    #"Replaced Errors in Score column" = Table.ReplaceErrorValues(#"Replaced Errors in Scored By column", {{"Score", null}}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Replaced Errors in Score column", "Text Before Delimiter", each Text.BeforeDelimiter([Name], " ("), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Inserted Text Before Delimiter",{"Name","Image URL", "Synopsis"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Text Before Delimiter", "Name"}}),
    #"Changed Episodes type from decimal to integer" = Table.TransformColumnTypes(#"Renamed Columns",{{"Episodes", Int64.Type}}),
    #"Duplicated Aired Column" = Table.DuplicateColumn(#"Changed Episodes type from decimal to integer", "Aired", "Airing Period"),
    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Aired Column",{"anime_id", "Name", "English name", "Other name", "Score", "Genres", "Type", "Episodes", "Aired", "Airing Period", "Premiered", "Status", "Producers", "Licensors", "Studios", "Source", "Duration", "Rating", "Rank", "Popularity", "Favorites", "Scored By", "Members"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Reordered Columns", "Aired", Splitter.SplitTextByDelimiter("to", QuoteStyle.Csv), {"Began Airing", "Ended Airing"}),
    #"Trimmed Ended Airing Column" = Table.TransformColumns(#"Split Column by Delimiter",{{"Ended Airing", Text.Trim, type text}}),
    #"Replaced ? with null in Ended Airing Column" = Table.ReplaceValue(#"Trimmed Ended Airing Column","?",null,Replacer.ReplaceValue,{"Ended Airing"}),
    #"Fixed Began Airing Through Custom Function" = Table.AddColumn(#"Replaced ? with null in Ended Airing Column", "Began Airing Fixed", each let
    Raw = [Began Airing],
    Value = if Raw = null then null else Text.Trim(Raw),
    Words = if Value = null then {} else Text.Split(Value, " "),
    IsNA = Value <> null and Text.Lower(Value) = "not available",
    IsYearOnly = Value <> null and Text.Length(Value) = 4 
                 and (try Number.From(Value) otherwise null) <> null,
    IsMonthYear = Value <> null and not IsYearOnly and List.Count(Words) = 2 
                  and (try Number.From(Words{1}) otherwise null) <> null
in
    if Value = null or IsNA then null
    else if IsYearOnly then #date(Number.From(Value), 1, 1)
    else if IsMonthYear then 
        #date(Number.From(Words{1}), Date.Month(Date.FromText(Words{0} & " 1, 2000")), 1)
    else Date.FromText(Value)),
    #"Removed Began Airing" = Table.RemoveColumns(#"Fixed Began Airing Through Custom Function",{"Began Airing"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Began Airing",{{"Began Airing Fixed", "Began Airing"}}),
    #"Changed Type from text to date" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Began Airing", type date}, {"Ended Airing", type date}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type from text to date",{"anime_id", "Name", "English name", "Other name", "Score", "Genres", "Type", "Episodes", "Began Airing", "Ended Airing", "Airing Period", "Premiered", "Status", "Producers", "Licensors", "Studios", "Source", "Duration", "Rating", "Rank", "Popularity", "Favorites", "Scored By", "Members"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns1", "Duration (min)", each let
    Raw = if [Duration] = null then null else Text.Trim([Duration]),

    HasHr = Raw <> null and Text.Contains(Raw, "hr"),
    Hours = if HasHr then Number.From(Text.Trim(Text.BeforeDelimiter(Raw, "hr"))) else 0,

    Remainder = if HasHr then Text.AfterDelimiter(Raw, "hr") else Raw,
    HasMin = Remainder <> null and Text.Contains(Remainder, "min"),
    Minutes = if HasMin then Number.From(Text.Trim(Text.BeforeDelimiter(Remainder, "min"))) else 0,

    Total = if Raw = null then null else Hours * 60 + Minutes
in
    Total),
    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom",{"anime_id", "Name", "English name", "Other name", "Score", "Genres", "Type", "Episodes", "Began Airing", "Ended Airing", "Airing Period", "Premiered", "Status", "Producers", "Licensors", "Studios", "Source", "Duration","Duration (min)", "Rating", "Rank", "Popularity", "Favorites", "Scored By", "Members"}),
    #"Replaced Errors in Rank Column" = Table.ReplaceErrorValues(#"Reordered Columns2", {{"Rank", null}}),
    #"Replaced Rank and Popularity zeros to null" = Table.ReplaceValue(#"Replaced Errors in Rank Column",0,null,Replacer.ReplaceValue,{"Rank", "Popularity"}),
    #"Replaced Value" = Table.ReplaceValue(#"Replaced Rank and Popularity zeros to null","Not available",null,Replacer.ReplaceValue,{"Airing Period"}),
    #"Grouped Rows" = Table.Group(#"Replaced Value", {"Name"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"Count", Order.Descending}})
in
    #"Sorted Rows"

*User_Anime_Rating:
let
    Source = Csv.Document(File.Contents("C:\Users\21650\Downloads\anime reviews\user-filtered.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"user_id", Int64.Type}, {"anime_id", Int64.Type}, {"rating", Int64.Type}})
in
    #"Changed Type"

*Countries:
let
    Source = Csv.Document(File.Contents("C:\Users\21650\Downloads\anime reviews\countries.csv"),[Delimiter=",", Columns=28, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}, {"iso3", type text}, {"iso2", type text}, {"numeric_code", Int64.Type}, {"phonecode", Int64.Type}, {"capital", type text}, {"currency", type text}, {"currency_name", type text}, {"currency_symbol", type text}, {"tld", type text}, {"native", type text}, {"population", Int64.Type}, {"gdp", Int64.Type}, {"region", type text}, {"region_id", Int64.Type}, {"subregion", type text}, {"subregion_id", Int64.Type}, {"nationality", type text}, {"area_sq_km", Int64.Type}, {"postal_code_format", type text}, {"postal_code_regex", type text}, {"timezones", type text}, {"latitude", type number}, {"longitude", type number}, {"emoji", type text}, {"emojiU", type text}, {"wikiDataId", type text}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"id", "name", "iso3", "iso2", "region", "subregion"})
in
    #"Removed Other Columns"

*User:
let
    Source = Csv.Document(File.Contents("C:\Users\21650\Downloads\anime reviews\users-details-enhanced-2023.csv"),[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Mal ID", Int64.Type}, {"Username", type text}, {"Gender", type text}, {"Birthday", type datetime}, {"Location", type text}, {"Joined", type datetime}, {"Days Watched", type number}, {"Mean Score", type number}, {"Watching", Int64.Type}, {"Completed", Int64.Type}, {"On Hold", Int64.Type}, {"Dropped", Int64.Type}, {"Plan to Watch", Int64.Type}, {"Total Entries", Int64.Type}, {"Rewatched", Int64.Type}, {"Episodes Watched", Int64.Type}, {"Country", type text}}),
    #"Extracted Date" = Table.TransformColumns(#"Changed Type",{{"Joined", DateTime.Date, type date}, {"Birthday", DateTime.Date, type date}}),
    #"Added Age Column" = Table.AddColumn(#"Extracted Date", "Age", each Number.RoundDown(Duration.Days(Date.From(DateTime.LocalNow()) - [Birthday]) / 365.25)),
    #"Added Years Active Column" = Table.AddColumn(#"Added Age Column", "Years Active", each Number.RoundDown(Duration.Days(Date.From(DateTime.LocalNow()) - [Joined]) / 365.25)),
    #"Changed Added Columns Types To Whole Number" = Table.TransformColumnTypes(#"Added Years Active Column",{{"Age", Int64.Type},{"Years Active", Int64.Type}}),
    #"Removed Location Column" = Table.RemoveColumns(#"Changed Added Columns Types To Whole Number",{"Location"}),
    #"Filtered Inactive Users Rows" = Table.SelectRows(#"Removed Location Column", each ([Days Watched] <> 0)),
    #"Filtered Rows" = Table.SelectRows(#"Filtered Inactive Users Rows", each [Total Entries] > 0),
    #"Removed False Ages" = Table.TransformColumns(#"Filtered Rows", {{"Age", each if _ < 5 or _ > 80 then null else _, type number}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed False Ages",{"Mal ID", "Username", "Gender", "Birthday", "Age", "Country", "Joined","Years Active", "Days Watched", "Mean Score", "Watching", "Completed", "On Hold", "Dropped", "Plan to Watch", "Total Entries", "Rewatched", "Episodes Watched"}),
    #"Added Rewatching Rate Column" = Table.AddColumn(#"Reordered Columns", "Rewatching Rate", each [Rewatched]/[Completed]),
    #"Added Completion Rate Column" = Table.AddColumn(#"Added Rewatching Rate Column", "Completion Rate", each [Completed]/[Total Entries]),
    #"Added Custom" = Table.AddColumn(#"Added Completion Rate Column", "Watcher Type", each if [Completed] < 100 then "Casual (<100)"
else if [Completed] <= 500 then "Average (100-500)"
else "Avid (500+)")
in
    #"Added Custom"

*Anime_Watch_Count:
let
    Source = User_Anime_Rating,
    #"Grouped Rows" = Table.Group(Source, {"anime_id"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Count", "Watch_Count"}}),
    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"Watch_Count", Order.Descending}})
in
    #"Sorted Rows"

*User_Watch_Count:
let
    Source = User_Anime_Rating,
    #"Grouped Rows" = Table.Group(Source, {"user_id"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"Count", Order.Descending}})
in
    #"Sorted Rows"

*Country_Rating_Sample:
let
    Source = User_Anime_Rating,
    #"Filtered Rows" = Table.SelectRows(Source, each ([rating] <> 0))
in
    #"Filtered Rows"

*Country_Lookup:
let
    Source = User,
    #"Removed Other Columns" = Table.SelectColumns(Source,{"Mal ID", "Country"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([Country] = "Brazil" or [Country] = "Canada" or [Country] = "France" or [Country] = "Germany" or [Country] = "Philippines" or [Country] = "Poland" or [Country] = "Russia" or [Country] = "United Kingdom" or [Country] = "United States")),
    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Mal ID"}, Country_Rating_Sample, {"user_id"}, "Country_Rating_Sample", JoinKind.Inner),
    #"Expanded Country_Rating_Sample" = Table.ExpandTableColumn(#"Merged Queries", "Country_Rating_Sample", {"rating"}, {"Country_Rating_Sample.rating"}),
    #"Added Custom" = Table.AddColumn(#"Expanded Country_Rating_Sample", "RandomSample", each Number.RandomBetween(0,1)),
    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each [RandomSample] <= 0.02),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows1",{"RandomSample"})
in
    #"Removed Columns"

*Backlog_Paradox_Sample:
let
    Source = User,
    #"Filtered Rows" = Table.SelectRows(Source, each [Total Entries] >= 20),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Username","Watcher Type",
 "Completed", "Plan to Watch", "Rewatched", "Rewatching Rate", "Completion Rate"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "RandomSample", each Number.RandomBetween(0,1)),
    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each [RandomSample] <= 0.005),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows1",{"RandomSample"})
in
    #"Removed Columns"

*Users Entries Status Grouped By Watcher Type:
let
    Source = User,
    #"Grouped Rows" = Table.Group(
        Source,
        {"Watcher Type"},
        {
            {"Completed", each List.Average([Completed]), type nullable number},
            {"On Hold", each List.Average([#"On Hold"]), type nullable number},
            {"Dropped", each List.Average([Dropped]), type nullable number},
            {"Plan To Watch", each List.Average([#"Plan to Watch"]), type nullable number}
        }
    ),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(
        #"Grouped Rows",
        {"Watcher Type"},
        "Status",
        "Avg Count"
    ),
    #"Added % of Type" = Table.AddColumn(
        #"Unpivoted Other Columns",
        "% of Type",
        each [#"Avg Count"] / List.Sum(
            Table.SelectRows(
                #"Unpivoted Other Columns",
                (r) => r[#"Watcher Type"] = [#"Watcher Type"]
            )[#"Avg Count"]
        )
    )
in
    #"Added % of Type"